version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: #changeMe##
      MYSQL_ROOT_PASSWORD:  #changeMe##
      MYSQL_PASSWORD:  #changeMe##
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
